#!/usr/bin/env php
<?php

use App\Calculator\Calculator;

require_once './vendor/autoload.php';

[, $a, $operation, $b] = $_SERVER['argv'];
$calculator = new Calculator();

echo $calculator->execute($a, $operation, $b);

echo PHP_EOL;
