#!/usr/bin/env php
<?php

use App\Calculator\Calculator;

require_once './vendor/autoload.php';

$a = $_SERVER['argv'][1] ?? null;
$operation = $_SERVER['argv'][2] ?? null;
$b = $_SERVER['argv'][3] ?? null;

$calculator = new Calculator();

echo $calculator->execute($a, $operation, $b);

echo PHP_EOL;
